language: node_js
env:
  global:
  - secure: ngfVcAjomZKTFgL+iLw/R6JIKb1kFzZlSPh+GV+C5KelwQwYk0iL3nheVFHEm327cbWKgTasfPntwAQ28RiAjVSN2RHp+N7pcwOFjZoH4Svy7HKQ4+ptQtiRdIyLPaJ8LJrOKtWRjy0x5u8mZRbCsX8uvYqB9cbHBFBtkrNwOKETS/9JRAmXL1Mc7Exxwh/MmW3UyEQoY0l6c9sbwEbj9E+3rk4UxZIojnCBRJ0GlT7baqozt7qUIzQLlQrlLNt1Q6a8kzetdIrgUQ1arn/LAQcv2XQGHOnjP7ow/nCkq+wIyB2DyrjEW5jzkvqoqqBwz2AxFfn7Ic8iCpR+W6PC34GMdSvELlMGI6vbS1d991f/rSpRP8ndm6gH1y3Y5a/s/xQqKIaFg7hyLCmWNp58ampM7Us1e+fX6NqELTr+wjW5SJt7RMYhpRUxgsgUwouJE4ey+C6OfvEqwE73FVQNQHv6GYadjkwqEoTDG2Kvws8qiYvVUuqV9Uri9dyVeorwWr8z1XX8B1vVkb112hNDKoO6Dhc58EvQLNi0C4VAMQD6o/o+w9O8RFnTaAvBvp9bDIwe04ZcQK2SqHL0sViYg7PvB+yw1vPM6KZevq7j4j6KCg9qZqUp8vO5YQ0pxCTsJK/SMpuOHuUeQYpsDRrfORRKdztPep8TjkCOaTOQ8mU=
node_js:
- stable
services:
- docker
script:
- npm run lint:js && git clone https://andrii482:$GithubToken_for_wooden-server-js_repository@github.com/482solutions/woden-server-js.git && docker-compose -f woden-server-js/docker-compose.yml up --build -d && npm i && npm run cypress:run
