version: '3.4'

services:

  ui:
    image: node:latest
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile_ui
    ports:
      - 3000:3000
#    network_mode: host
  
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    network_mode: bridge
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - ./build:/root/build
    ports:
     - 80:80
