# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - workflow_actions

#  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
        git clone https://andrii482:${{secrets.c0c5e002db7d9fc089c5091bdf5a23adff97391e}}@github.com/482solutions/woden-server-js
        docker-compose up --build  
#    with:
#        repository: https://github.com/482solutions/woden-server-js
#        token: ${{secrets.woden_server_js_workflow_actions_repo}}
#    - run: npm i
#    - run: npm run lint:js
#    - run: npm run build
#    - run: npm test
      env:
        CI: true
