# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
 #       env:
 #         PASS: ${{ secrets.PASSWORD }}

      - name: Installing dependencies and start server
        run: |
          npm i
          npm run fix:js
          npm run lint:js
          sudo docker system prune -a -f
          git clone https://andrii482:${{ secrets.PASSWORD }}@github.com/482solutions/woden-network.git
          cd woden-network && sudo chmod 777 ./deploy.sh && sudo ./deploy.sh
          cd ..
          git clone https://andrii482:${{ secrets.PASSWORD }}@github.com/482solutions/woden-server-js.git
          cd woden-server-js && docker-compose up --build -d
          cd ..
          npm run start -d & sleep 40

      - name: Get stucture
        run: ls -a

      - name: Run Cypress tests with Chrome
        run: npm run cy:run:chrome

#      - uses: actions/upload-artifact@master
#        if: failure()
#        with:
#          name: screenshots
#          path:  cypress/screenshots

      - uses: actions/upload-artifact@master
        with:
          name: videos
          path: cypress/videos
