# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run fix:js
      - run: npm run lint:js
      - run: docker system prune -a -f
      - run: git clone https://andrii482:$GITHUBTOKEN@github.com/482solutions/woden-network.git
      - run: cd woden-network && sudo chmod 777 ./deploy.sh && sudo ./deploy.sh
      - run: cd ..
      - run: git clone https://andrii482:$GITHUBTOKEN@github.com/482solutions/woden-server-js.git
      - run: cd woden-server-js && docker-compose up --build -d
      - run: cd ..
      - run: npm run start -d & sleep 40
      - name: Run Cypress tests with Chrome
        run: npm run cy:run:chrome
      - run: npm run coverage
