# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:

  pull_request:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
        git clone https://andrii482:c0c5e002db7d9fc089c5091bdf5a23adff97391e@github.com/482solutions/woden-server-js.git  -b feature/WGRND-597 --single-branch 
        docker-compose -f ./woden-server-js/docker-compose.yml up --build -d 
        npm i
        npm start 
        git clone https://andrii482:c0c5e002db7d9fc089c5091bdf5a23adff97391e@github.com/482solutions/woden-ui.git  -b  WGRND-553 --single-branch 
        cd woden-ui 
        npm i 
        npm run cypress:run    
      env:
        CI: true
