# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
#       - run: npm run fix:js
#       - run: npm run lint:js
      - run: sudo docker system prune -a -f
      - run: git clone https://andrii482:$GithubToken@github.com/482solutions/woden-network.git
      - run: cd woden-network && sudo chmod 777 ./deploy.sh && sudo ./deploy.sh
      - run: cd ..
      - run: git clone https://andrii482:$GithubToken@github.com/482solutions/woden-server-js.git
      - run: cd woden-server-js && docker-compose up --build -d
#       - run: sleep 30
      - run: cd ..
      - run: npm run start -d & sleep 40
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on: 'http://localhost:3000'
#           wait-on-timeout: 120
          record: true
          parallel: true
#          browser: chrome
          group: 'Actions'
          spec: "cypress/integration/*/*.feature"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.WODEN_TOKEN }}
      - run: npm run coverage

#          start: npm run startci & sleep 10
#          wait-on: 'http://localhost:3000'
#          wait-on-timeout: 120

